name: Upload to WordPress

on:
  repository_dispatch:
    types: [upload-zip]
  workflow_dispatch:

# Cấp quyền ghi cho GITHUB_TOKEN để push file log về repo
permissions:
  contents: write

jobs:
  # JOB 1: Đọc config và tạo ma trận động cho job sau
  setup:
    runs-on: ubuntu-latest
    outputs:
      sites_matrix: ${{ steps.set_matrix.outputs.sites }}
    steps:
      - name: Checkout ktbupload repo
        uses: actions/checkout@v4

      - name: Read sites config and set matrix
        id: set_matrix
        run: |
          SITES_JSON=$(jq -c '.sites' ktbupload/config.json)
          echo "sites=${SITES_JSON}" >> $GITHUB_OUTPUT

  # JOB 2: Upload file, chạy song song cho mỗi site trong ma trận
  upload:
    needs: setup # Phải chạy sau khi job setup hoàn thành
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Nếu 1 site lỗi, các site khác vẫn tiếp tục
      matrix:
        # Tạo ma trận từ output của job setup
        site: ${{ fromJson(needs.setup.outputs.sites_matrix) }}

    steps:
      - name: Checkout ktbupload repo
        uses: actions/checkout@v4
        with:
          path: ktbupload

      - name: Checkout ktb-image repo
        uses: actions/checkout@v4
        with:
          repository: ktbhub/ktb-image
          path: ktb-image
          token: ${{ secrets.KTBHUB_PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Upload and Process for ${{ matrix.site.slug }}
        id: upload_process
        env:
          # Truyền toàn bộ thông tin của site hiện tại vào script
          SITE_CONFIG_JSON: ${{ toJSON(matrix.site) }}
          
          # Truyền TẤT CẢ secrets của VPS vào môi trường.
          # Script Node.js sẽ tự động chọn đúng secret cần dùng.
          KTBTEE_VPS_HOST: ${{ secrets.KTBTEE_VPS_HOST }}
          KTBTEE_VPS_USERNAME: ${{ secrets.KTBTEE_VPS_USERNAME }}
          KTBTEE_SSH_PRIVATE_KEY: ${{ secrets.KTBTEE_SSH_PRIVATE_KEY }}
          KTBTEE_VPS_PORT: ${{ secrets.KTBTEE_VPS_PORT }}
          
          WHATWILLWEAR_VPS_HOST: ${{ secrets.WHATWILLWEAR_VPS_HOST }}
          WHATWILLWEAR_VPS_USERNAME: ${{ secrets.WHATWILLWEAR_VPS_USERNAME }}
          WHATWILLWEAR_SSH_PRIVATE_KEY: ${{ secrets.WHATWILLWEAR_SSH_PRIVATE_KEY }}
          WHATWILLWEAR_VPS_PORT: ${{ secrets.WHATWILLWEAR_VPS_PORT }}
          
          # LƯU Ý: Khi có site mới, bạn chỉ cần thêm secrets của nó vào đây và vào repo settings
          
        run: node ktbupload/upload-script.js
      
      - name: Commit and push log file
        # Chỉ chạy nếu có file được upload thành công
        if: success() && steps.upload_process.outputs.uploaded_count > 0
        run: |
          cd ktbupload
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uploaded_files_${{ matrix.site.slug }}.log
          git commit -m "Update log for ${{ matrix.site.slug }}" || echo "No changes to commit"
          git push

  # JOB 3: Gửi báo cáo tổng hợp sau khi tất cả các job upload hoàn tất
  report:
    needs: upload
    if: always() # Luôn chạy dù các job upload thành công hay thất bại
    runs-on: ubuntu-latest
    steps:
      - name: Send Summary Report to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ KTB Uploader - Workflow Hoàn Tất!
            
            Trạng thái chung: ${{ needs.upload.result }}
            Xem chi tiết tại: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
